export const articleInfo = [
  {
    id: 0,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'ABOUT CORONAVIRUS',
    date: 'August 26, 2016',
    author: 'Patrick Panuncillon',
    title: 'Talking about COVID-19',
    desc: 'What is a coronavirus? Coronaviruses are a large family of viruses which may cause illness in animals or humans. In humans, several...',
  },
  {
    id: 1,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'COVID-19 PARENTING',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Washing hands to ward off COVID-19',
    desc: 'Be willing to talk. They will already have heard something. Silence and secrets do not protect our children. Honesty and openness do help...',
  },
  {
    id: 2,
    img_src: '../../assets/mock-images/youth1.svg',
    tag: 'YOUTH',
    tag_meta: 'FREEDOM FOR GIRLS',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Hear Asseta, Meleichi and Kharda’s stories',
    desc: 'Sharing positive stories of change can be a good way to help mothers be more open...',
  },
  {
    id: 3,
    img_src: '../../assets/mock-images/youth2.svg',
    tag: 'YOUTH',
    tag_meta: 'FREEDOM FOR GIRLS',
    date: 'July 14, 2016',
    author: 'Robyn Collinge',
    title: 'Empowering girls and promoting education',
    desc: 'Growing strong, healthily and with increasing movement control. Children at age four...',
  },
  {
    id: 4,
    img_src: '../../assets/mock-images/parent1.svg',
    tag: 'PARENTS & CAREGIVERS',
    tag_meta: 'NUTRITION',
    date: 'June 29, 2016',
    author: 'Florian Gendrault',
    title: 'Establishing stronger connection with your toddler',
    desc: 'When to introduce your baby to complementary foods and why getting the...',
  },
  {
    id: 5,
    img_src: '../../assets/mock-images/parent2.svg',
    tag: 'PARENTS & CAREGIVERS',
    tag_meta: 'EARLY LIFE TIPS',
    date: 'July 14, 2016',
    author: 'Robyn Collinge',
    title: 'When to start with complementary solid foods',
    desc: 'Learning to communicate with your baby. Both parents should actively interact with the baby...',
  },
  {
    id: 6,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'ABOUT CORONAVIRUS',
    date: 'August 26, 2016',
    author: 'Patrick Panuncillon',
    title: 'Talking about COVID-19',
    desc: 'What is a coronavirus? Coronaviruses are a large family of viruses which may cause illness in animals or humans. In humans, several...',
  },
  {
    id: 7,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'COVID-19 PARENTING',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Washing hands to ward off COVID-19',
    desc: 'Be willing to talk. They will already have heard something. Silence and secrets do not protect our children. Honesty and openness do help...',
  },
  {
    id: 8,
    img_src: '../../assets/mock-images/youth1.svg',
    tag: 'YOUTH',
    tag_meta: 'FREEDOM FOR GIRLS',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Hear Asseta, Meleichi and Kharda’s stories',
    desc: 'Sharing positive stories of change can be a good way to help mothers be more open...',
  },
];

export const aboutCoronavirusArticles = [
  {
    id: 0,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: '',
    date: '',
    author: '',
    title: 'About Coronavirus',
    desc: '',
  },
  {
    id: 1,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Protecting Yourself and Others from COVID-19',
    desc: '',
  },
  {
    id: 2,
    img_src: '../../assets/mock-images/myths.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Myths',
    desc: '',
  },
  {
    id: 3,
    img_src: '',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Washing hands to ward off COVID-19',
    desc: '',
  },
];

export const studentToolkitArticles = [
  {
    id: 0,
    img_src: '../../assets/mock-images/responsibility.svg',
    tag: 'STUDENT TOOLKIT',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Know Your Responsibility',
    desc: '',
  },
  {
    id: 1,
    img_src: '../../assets/mock-images/fact.svg',
    tag: 'STUDENT TOOLKIT',
    tag_meta: '',
    date: '',
    author: '',
    title: 'COVID-19 Myths and Facts (Student Edition)',
    desc: '',
  },
  {
    id: 2,
    img_src: '',
    tag: 'STUDENT TOOLKIT',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Feeling Lonely',
    desc: '',
  },
  {
    id: 3,
    img_src: '',
    tag: 'STUDENT TOOLKIT',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Become a COVID-19 Student Expert',
    desc: '',
  },
];

export const covidParentingArticles = [
  {
    id: 0,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'COVID-19 PARENTING',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Talking about COVID-19',
    desc: '',
  },
  {
    id: 1,
    img_src: '../../assets/mock-images/keep_calm.svg',
    tag: 'COVID-19 PARENTING',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Keep Calm & Manage Stress',
    desc: '',
  },
  {
    id: 2,
    img_src: '../../assets/mock-images/tip1.svg',
    tag: 'COVID-19 PARENTING',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Tip 1: One-on-One Time',
    desc: '',
  },
  {
    id: 3,
    img_src: '../../assets/mock-images/tip2.svg',
    tag: 'COVID-19 PARENTING',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Tip 2: Routine Up',
    desc: '',
  },
];

export const healthWorkerArticles = [
  {
    id: 0,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'HEALTH WORKERS',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Facility Manager Guidelines',
    desc: '',
  },
  {
    id: 1,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'HEALTH WORKERS',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Coping with COVID-19 Stress',
    desc: '',
  },
  {
    id: 2,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'HEALTH WORKERS',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Protecting Yourself at Work From COVID-19',
    desc: '',
  },
  {
    id: 3,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'HEALTH WORKERS',
    tag_meta: '',
    date: '',
    author: '',
    title: 'Communicating With COVID-19 Patients and Visitors',
    desc: '',
  },
];

export const mobileHomeArticles = [
  {
    id: 0,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'ABOUT CORONAVIRUS',
    date: 'August 26, 2016',
    author: 'Patrick Panuncillon',
    title: 'Talking about COVID-19',
    desc: 'What is a coronavirus? Coronaviruses are a large family of viruses which may cause illness in animals or humans. In humans, several...',
  },
  {
    id: 1,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'COVID-19 PARENTING',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Washing hands to ward off COVID-19',
    desc: 'Be willing to talk. They will already have heard something. Silence and secrets do not protect our children. Honesty and openness do help...',
  },
  {
    id: 2,
    img_src: '../../assets/mock-images/youth1.svg',
    tag: 'YOUTH',
    tag_meta: 'FREEDOM FOR GIRLS',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Hear Asseta, Meleichi and Kharda’s stories',
    desc: 'Sharing positive stories of change can be a good way to help mothers be more open...',
  },
];

export const desktopCoronaArticles = [
  {
    id: 0,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'ABOUT CORONAVIRUS',
    date: 'August 26, 2016',
    author: 'Patrick Panuncillon',
    title: 'Talking about COVID-19',
    desc: 'What is a coronavirus? Coronaviruses are a large family of viruses which may cause illness in animals or humans. In humans, several...',
  },
  {
    id: 1,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'COVID-19 PARENTING',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Washing hands to ward off COVID-19',
    desc: 'Be willing to talk. They will already have heard something. Silence and secrets do not protect our children. Honesty and openness do help...',
  },
  {
    id: 2,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'COVID-19 PARENTING',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Washing hands to ward off COVID-19',
    desc: 'Be willing to talk. They will already have heard something. Silence and secrets do not protect our children. Honesty and openness do help...',
  },
];

export const desktopStudentArticles = [
  {
    id: 0,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'ABOUT CORONAVIRUS',
    date: 'August 26, 2016',
    author: 'Patrick Panuncillon',
    title: 'Talking about COVID-19',
    desc: 'What is a coronavirus? Coronaviruses are a large family of viruses which may cause illness in animals or humans. In humans, several...',
  },
  {
    id: 1,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'COVID-19 PARENTING',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Washing hands to ward off COVID-19',
    desc: 'Be willing to talk. They will already have heard something. Silence and secrets do not protect our children. Honesty and openness do help...',
  },
  {
    id: 2,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'COVID-19 PARENTING',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Washing hands to ward off COVID-19',
    desc: 'Be willing to talk. They will already have heard something. Silence and secrets do not protect our children. Honesty and openness do help...',
  },
];

export const desktopParentingArticles = [
  {
    id: 0,
    img_src: '../../assets/mock-images/covid.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'ABOUT CORONAVIRUS',
    date: 'August 26, 2016',
    author: 'Patrick Panuncillon',
    title: 'Talking about COVID-19',
    desc: 'What is a coronavirus? Coronaviruses are a large family of viruses which may cause illness in animals or humans. In humans, several...',
  },
  {
    id: 1,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'COVID-19 PARENTING',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Washing hands to ward off COVID-19',
    desc: 'Be willing to talk. They will already have heard something. Silence and secrets do not protect our children. Honesty and openness do help...',
  },
  {
    id: 2,
    img_src: '../../assets/mock-images/covid2.svg',
    tag: 'CORONAVIRUS (COVID-19)',
    tag_meta: 'COVID-19 PARENTING',
    date: 'August 19, 2016',
    author: 'Robyn Collinge',
    title: 'Washing hands to ward off COVID-19',
    desc: 'Be willing to talk. They will already have heard something. Silence and secrets do not protect our children. Honesty and openness do help...',
  },
];
